### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by darklight213**
very small fix for readme

### CODE REVIEW

**Review by KerelKarel — APPROVED** [review]
nice

**Review by Lars2203 — CHANGES_REQUESTED** [review]
nah

**Review by JennieAV — APPROVED** [review]
you removed a space

**Review by MooonStarr — APPROVED** [review]
Contains the solution to all of life's problems. Don't know if I should approve of this, sorry.

**Review by jochem06 — APPROVED** [review]
fine

**Review by Lars2203 — APPROVED** [review]

**Review by MooonStarr — CHANGES_REQUESTED** [review]
no

**Pull request merged**
